config/routes.rb
Fxmobiledj::Application.routes.draw do

  match 'acerca-de-nosotros' => 'home#about_us', :as => :about_us
  match 'galeria' => 'home#gallery', :as => :gallery

   root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about_us
  end

  def gallery
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<!-- ########################### HEADER ########################### -->
		<header id="header" class="group">
			<h1 id="logo" class="four columns"><%= link_to image_tag("fx-logo.png"), root_path %></h1>
			<nav id="nav" class="nav twelve columns">
				<ul id="navigation" class="sf-menu">
					<li>
					  <%= link_to "Home", root_path %>
                    </li>
                    <li>
                      <%= link_to "Galeria de Fotos", gallery_path %>
                    </li>
					<li>
						<%= link_to "Acerca de Nosotros", about_us_path %>
					</li>
                  </ul><!-- /navigation -->
                  <br>
                  <div style="float:right;">
                    <div class="fb-like" data-href="http://www.fxmobiledj.com/" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
                  </div>
			</nav><!-- /nav -->
        </header><!-- /header -->
            <div id="fb-root"></div>
            <script>(function(d, s, id) {
              var js, fjs = d.getElementsByTagName(s)[0];
              if (d.getElementById(id)) return;
              js = d.createElement(s); js.id = id;
              js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1&appId=191190294401149";
              fjs.parentNode.insertBefore(js, fjs);
              }(document, 'script', 'facebook-jssdk'));</script>

app/views/home/about_us.html.erb
<div id="wrap">
	<div class="container">
  <%= render :partial => "header" %>
	<!-- ########################### MAIN ########################### -->
<h3 class="section-title">Acerca de Nosotros</h3>

<div class="row">
	<div class="sixteen columns">

		<article class="post static">
			<div class="post-body">
        <p><%= image_tag ("acerca_de.jpg"), :class=>"scale-with-grid alignleft", :style => "height:360px" %> Somos una empresa que a lo largo del camino, hemos vivido con nuestros clientes cada emoción y sentimiento, planeando juntos, cada detalle acerca del espectáculo musical de su boda.</p>

          <p>Con mas de 15 años desempeñándonos en el mundo de la música, nuestros DJs cuentan con la preparación y experiencia para hacer de tu boda, un acontecimiento inolvidable, esto es FX mobile DJ.</p>

          <p>Atentos, puntuales, formales y con las ganas de realizar tu evento, es como nuestro equipo, se presentara ese día, el cual, entendemos es irrepetible.</p>

          <p> Contratar FX mobile DJ no es solo elegir un servicio de música, es obtener   la tranquilidad de dejar en manos expertas, el día mas importante de tu vida, tu boda.       </p>
          <p>.</p>
          <p>.</p>

				<h4>Servicios</h4>
        <p>
          <ul>
          <li>°Sonido profesional</li>
          <li>°Iluminación con leds y cabezas móviles</li>
          <li>°Accesorios de animación</li>
          <li>°Pirotecnia en Vals</li>
          <li>°Iluminación arquitectónica ( kolorados y/o leds)</li>
          <li>°Pantalla y proyector</li>
          <li>°Pista Iluminada</li>
          <li>°Disparos de confeti</li>
          <li>°Audio y micrófono para civil</li>
          <li>°Violín o saxofón durante la cena</li>
        </ul>
        </p>
				<h4>Paquetes</h4>
        <p> Comunícate con nosotros para realizar una cotización detallada y precisa, de acuerdo a las necesidades de tu evento. </p>

       			</div>
		</article><!-- /post -->

	</div><!-- /sixteen columns -->
</div><!-- /row -->

	</div><!-- /container -->

</div><!-- /wrap -->

</body>
</html>

app/views/home/gallery.html.erb
	<!-- Sharethis
  ================================================== -->
	<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
	<script type="text/javascript">stLight.options({publisher: "ur-98c5c079-582-4b9f-ed66-a6a2eee6d3c"});</script>

<div id="wrap">
	<div class="container">
    <%= render :partial => "header" %>

		<!-- ########################### MAIN ########################### -->

<h3 class="section-title">Galeria de Fotos</h3>

<div class="row">
	<div class="sixteen columns">

		<ol class="listing group">
			<li class="one-third column alpha">
				<div class="latest-item gallery-item">
          <%= link_to (image_tag("03.jpg", :alt => "", :class => "scale-with-grid")), image_path("03.jpg"), :rel => "prettyPhoto[pp_gal]", "data-rel" => "prettyPhoto[pp_gal]" %>
					<p class="album-info">
						<span class="sub-head"></span>
					</p>
				</div><!-- /latest-album -->
			</li>
			<li class="one-third column">
				<div class="latest-item gallery-item">
          <%= link_to (image_tag("04.jpg", :alt => "", :class => "scale-with-grid")), image_path("04.jpg"), :rel => "prettyPhoto[pp_gal]", "data-rel" => "prettyPhoto[pp_gal]" %>

					<p class="album-info">
						<span class="sub-head"></span>
					</p>
				</div><!-- /latest-album -->
			</li>
			<li class="one-third column omega">
				<div class="latest-item gallery-item">
          <%= link_to (image_tag("05.jpg", :alt => "", :class => "scale-with-grid")), image_path("05.jpg"), :rel => "prettyPhoto[pp_gal]", "data-rel" => "prettyPhoto[pp_gal]" %>

          <p class="album-info">
						<span class="sub-head"></span>
					</p>
				</div><!-- /latest-album -->
			</li>
			<li class="one-third column alpha">
				<div class="latest-item gallery-item">
          <%= link_to (image_tag("06.jpg", :alt => "", :class => "scale-with-grid")), image_path("06.jpg"), :rel => "prettyPhoto[pp_gal]", "data-rel" => "prettyPhoto[pp_gal]" %>

					<p class="album-info">
						<span class="sub-head"></span>
					</p>
				</div><!-- /latest-album -->
			</li>
			<li class="one-third column">
				<div class="latest-item gallery-item">
          <%= link_to (image_tag("07.jpg", :alt => "", :class => "scale-with-grid")), image_path("07.jpg"), :rel => "prettyPhoto[pp_gal]", "data-rel" => "prettyPhoto[pp_gal]" %>

					<p class="album-info">
						<span class="sub-head"></span>
					</p>
				</div><!-- /latest-album -->
			</li>
			<li class="one-third column omega">
				<div class="latest-item gallery-item">
          <%= link_to (image_tag("08.jpg", :alt => "", :class => "scale-with-grid")), image_path("08.jpg"), :rel => "prettyPhoto[pp_gal]", "data-rel" => "prettyPhoto[pp_gal]" %>
					<p class="album-info">
						<span class="sub-head"></span>
					</p>
				</div><!-- /latest-album -->
			</li>
      <li class="one-third column alpha">
				<div class="latest-item gallery-item">
          <%= link_to (image_tag("10.jpg", :alt => "", :class => "scale-with-grid")), image_path("10.jpg"), :rel => "prettyPhoto[pp_gal]", "data-rel" => "prettyPhoto[pp_gal]" %>

					<p class="album-info">
						<span class="sub-head"></span>
					</p>
				</div><!-- /latest-album -->
			</li>
			<li class="one-third column">
				<div class="latest-item gallery-item">
          <%= link_to (image_tag("11.jpg", :alt => "", :class => "scale-with-grid")), image_path("11.jpg"), :rel => "prettyPhoto[pp_gal]", "data-rel" => "prettyPhoto[pp_gal]" %>

					<p class="album-info">
						<span class="sub-head"></span>
					</p>
				</div><!-- /latest-album -->
			</li>
			<li class="one-third column omega">
				<div class="latest-item gallery-item">
          <%= link_to (image_tag("12.jpg", :alt => "", :class => "scale-with-grid")), image_path("12.jpg"), :rel => "prettyPhoto[pp_gal]", "data-rel" => "prettyPhoto[pp_gal]" %>
					<p class="album-info">
						<span class="sub-head"></span>
					</p>
				</div><!-- /latest-album -->
			</li>

      <li class="one-third column alpha">
        <div class="latest-item gallery-item">
          <%= link_to (image_tag("13.jpg", :alt => "", :class => "scale-with-grid")), image_path("13.jpg"), :rel => "prettyPhoto[pp_gal]", "data-rel" => "prettyPhoto[pp_gal]" %>

          <p class="album-info">
            <span class="sub-head"></span>
          </p>
        </div><!-- /latest-album -->
      </li>
      <li class="one-third column">
        <div class="latest-item gallery-item">
          <%= link_to (image_tag("14.jpg", :alt => "", :class => "scale-with-grid")), image_path("14.jpg"), :rel => "prettyPhoto[pp_gal]", "data-rel" => "prettyPhoto[pp_gal]" %>

          <p class="album-info">
            <span class="sub-head"></span>
          </p>
        </div><!-- /latest-album -->
      </li>
      <li class="one-third column omega">
        <div class="latest-item gallery-item">
          <%= link_to (image_tag("15.jpg", :alt => "", :class => "scale-with-grid")), image_path("15.jpg"), :rel => "prettyPhoto[pp_gal]", "data-rel" => "prettyPhoto[pp_gal]" %>
          <p class="album-info">
            <span class="sub-head"></span>
          </p>
        </div><!-- /latest-album -->
      </li>

    </ol><!-- /gallery -->

	</div><!-- /sixteen columns -->
  </div><!-- /row -->

</div><!-- /container -->
</div><!-- /wrap -->

app/views/home/index.html.erb
<div id="wrap">
	<div class="container">
    <%= render :partial => "header" %>
    <!-- ########################### SLIDER ########################### -->
		<div class="container slider">
			<div class="sixteen columns">

				<div class="flexslider">
				  <ul class="slides">
				    <li>
				      <a href="#">
					      <%= image_tag ("01slide.jpg") %>
					      <div class="slide-text">
					      	<h2>Fxmobiledj</h2>
					      </div>
				      </a>
				    </li>
				    <li>
				      <a href="#">
					      <%= image_tag ("02slide.jpg") %>
					      <div class="slide-text">
					      	<h2>Fxmobiledj</h2>
					      </div>
				      </a>
				    </li>
				    <li>
				      <a href="#">
					      <%= image_tag ("03slidereplace.jpg") %>
					      <div class="slide-text">
					      	<h2>Fxmobiledj</h2>
					      </div>
				      </a>
            </li>
            <li>
				      <a href="#">
					      <%= image_tag ("04slide.jpg") %>
					      <div class="slide-text">
					      	<h2>Fxmobiledj</h2>
					      </div>
				      </a>
				    </li>
				  </ul>
				</div>
			</div><!-- /sixteen columns -->
		</div><!-- /slider -->
	<!-- ########################### MAIN ########################### -->
	<div class="row">
		<div class="sixteen columns">
			<aside class="four columns alpha sidebar">
			</aside><!-- /sidebar -->
		</div><!-- /sixteen columns -->
	</div><!-- /row -->
</div><!-- /container -->


</div><!-- /wrap -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-30378589-1']);
  _gaq.push(['_setDomainName', 'fxmobiledj.com']);
  _gaq.push(['_trackPageview']);

  (function() {
   var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
   ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
   })();

</script>

app/views/layouts/_footer.html.erb
	<!-- ########################### FOOTER ########################### -->
	<div id="footer-wrap">
		<div class="container">
			<footer id="footer" class="sixteen columns">
				<div class="four columns widget-area alpha">
					<div class="widget group">
						<h3 class="widget-title">Mapa del Sitio</h3>
            <ul>
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Galeria de Fotos", gallery_path %></li>
              <li><%= link_to "Acerca de Nosotros", about_us_path %></li>
            </ul>
					</div><!-- /widget -->
				</div><!-- /widget-area -->

				<div class="four columns widget-area" >
					<div class="widget group">
						<h3 class="widget-title">Contactanos</h3>
						<ul>
              <li>Tel. 8347 0826</li>
              <li>Nextel 84758650</li>
              <li><a>info@fxmobiledj.com</a></li>
              <li><a>infodj@fxmobiledj.com</a></li>
						</ul>
					</div><!-- /widget -->
				</div><!-- /widget-area -->

        <div class="four columns widget-area">
          <div class="widget group">
            <h3 class="widget-title">Sitio</h3>
            <ul>
              <li><%= link_to "www.fxmobiledj.com", root_path %></li>
              <li><a></a></li>
						</ul>
          </div><!-- /widget -->
        </div><!-- /widget-area -->

        <div class="four columns widget-area omega">
					<div class="widget group">
				        <h3 class="widget-title">SOCIAL</h3>
                <a href="#" class="icn twitter">Twitter</a>
                <a href="http://www.facebook.com/Fxmobiledj?ref=ts&fref=ts" class="icn facebook" target="_blank">Facebook</a>
                <a href="#" class="icn gplus">Google+</a>
				    </div><!-- /widget -->
				</div><!-- /widget-area -->
			</footer><!-- /footer -->
		</div><!-- /container -->
	</div><!-- /footer-wrap -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
  <title>Fxmobiledj</title>
  <meta charset="utf-8">
  <%#= stylesheet_link_tag    'application', media: 'all' %>
  <%= stylesheet_link_tag    'skeleton', 'style', 'mediaqueries', 'flexslider', 'default', media: 'all' %>
  <%= javascript_include_tag 'jquery', 'jquery_ujs', 'hyphenator','jquery-1.8.2.min','jquery.equalHeights','jquery.fitvids','jquery.flexslider-min','jquery.prettyPhoto','modernizr','scripts','superfish'  %>
  <%#= javascript_include_tag 'application' %>
	<!-- Basic Page Needs
  ================================================== -->
	<meta name="description" content="">
	<meta name="author" content="">
	<!-- Mobile Specific Metas
  ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- CSS
  ================================================== -->
	<link href='http://fonts.googleapis.com/css?family=Lato:400,900,400italic' rel='stylesheet' type='text/css'>
	<!-- Favicons
	================================================== -->
	<link rel="shortcut icon" href="images/favicon.ico">
	<link rel="apple-touch-icon" href="images/apple-touch-icon.png">
	<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">

	<!-- Javascript
  ================================================== -->
	<script src="http://maps.google.com/maps/api/js?sensor=false"></script>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= render :partial => "layouts/footer" %>

</body>
</html>